import { MigrationInterface, QueryRunner } from 'typeorm';

type SeedValue = string | number | boolean | null;
type SeedRow = Record<string, SeedValue>;

export class SeedSampleData1714000001000 implements MigrationInterface {
  name = 'SeedSampleData1714000001000';

  private async insertRows(
    queryRunner: QueryRunner,
    table: string,
    columns: string[],
    rows: SeedRow[],
  ): Promise<void> {
    if (!rows.length) return;

    const escapedColumns = columns.map((column) => `\`${column}\``).join(', ');
    const placeholders = rows
      .map(() => `(${columns.map(() => '?').join(', ')})`)
      .join(',\n');
    const values = rows.flatMap((row) => columns.map((column) => row[column]));

    await queryRunner.query(
      `INSERT INTO \`${table}\` (${escapedColumns}) VALUES ${placeholders}`,
      values,
    );
  }

  public async up(queryRunner: QueryRunner): Promise<void> {
    const passwordHash =
      '$2b$10$CwTycUXWue0Thq9StjUM0uJ8UnQzwEPN5tdnOSFgoL5qWqP6z4GuO';

    await this.insertRows(
      queryRunner,
      'roles',
      ['id', 'name', 'description'],
      [
        { id: 1, name: 'admin', description: 'Quản trị viên toàn hệ thống' },
        {
          id: 2,
          name: 'staff',
          description: 'Nhân viên xử lý đơn hàng và hỗ trợ khách hàng',
        },
        {
          id: 3,
          name: 'member',
          description: 'Thành viên mua hàng trên website',
        },
      ],
    );

    await this.insertRows(
      queryRunner,
      'users',
      [
        'id',
        'email',
        'name',
        'phone',
        'password',
        'avatar',
        'provider',
        'provider_id',
        'role_id',
        'status',
        'email_verified_at',
      ],
      [
        {
          id: 1,
          email: 'admin@example.com',
          name: 'Quản trị viên hệ thống',
          phone: '0901000001',
          password: passwordHash,
          avatar: null,
          provider: 'local',
          provider_id: null,
          role_id: 1,
          status: 'active',
          email_verified_at: '2026-04-01 08:00:00',
        },
        {
          id: 2,
          email: 'staff@example.com',
          name: 'Nhân viên hệ thống',
          phone: '0901000002',
          password: passwordHash,
          avatar: null,
          provider: 'local',
          provider_id: null,
          role_id: 2,
          status: 'active',
          email_verified_at: '2026-04-01 08:05:00',
        },
        {
          id: 3,
          email: 'member@example.com',
          name: 'Thành viên hệ thống',
          phone: '0901000003',
          password: passwordHash,
          avatar: null,
          provider: 'local',
          provider_id: null,
          role_id: 3,
          status: 'active',
          email_verified_at: '2026-04-01 08:10:00',
        },
        {
          id: 4,
          email: 'staff02@ecommerce.test',
          name: 'Lê Nhân Viên 02',
          phone: '0901000004',
          password: passwordHash,
          avatar: null,
          provider: 'local',
          provider_id: null,
          role_id: 2,
          status: 'active',
          email_verified_at: '2026-04-01 08:15:00',
        },
        {
          id: 5,
          email: 'staff03@ecommerce.test',
          name: 'Phạm Nhân Viên 03',
          phone: '0901000005',
          password: passwordHash,
          avatar: null,
          provider: 'local',
          provider_id: null,
          role_id: 2,
          status: 'inactive',
          email_verified_at: null,
        },
        {
          id: 6,
          email: 'customer01@example.com',
          name: 'Nguyễn Minh Anh',
          phone: '0912000001',
          password: passwordHash,
          avatar: null,
          provider: 'local',
          provider_id: null,
          role_id: 3,
          status: 'active',
          email_verified_at: '2026-04-02 09:00:00',
        },
        {
          id: 7,
          email: 'customer02@example.com',
          name: 'Trần Quốc Bảo',
          phone: '0912000002',
          password: passwordHash,
          avatar: null,
          provider: 'local',
          provider_id: null,
          role_id: 3,
          status: 'active',
          email_verified_at: '2026-04-02 09:05:00',
        },
        {
          id: 8,
          email: 'customer03@example.com',
          name: 'Lê Hoàng Chi',
          phone: '0912000003',
          password: passwordHash,
          avatar: null,
          provider: 'local',
          provider_id: null,
          role_id: 3,
          status: 'active',
          email_verified_at: '2026-04-02 09:10:00',
        },
        {
          id: 9,
          email: 'customer04@example.com',
          name: 'Phạm Gia Huy',
          phone: '0912000004',
          password: passwordHash,
          avatar: null,
          provider: 'local',
          provider_id: null,
          role_id: 3,
          status: 'active',
          email_verified_at: '2026-04-02 09:15:00',
        },
        {
          id: 10,
          email: 'customer05@example.com',
          name: 'Vũ Khánh Linh',
          phone: '0912000005',
          password: passwordHash,
          avatar: null,
          provider: 'local',
          provider_id: null,
          role_id: 3,
          status: 'active',
          email_verified_at: '2026-04-02 09:20:00',
        },
        {
          id: 11,
          email: 'customer06@example.com',
          name: 'Đỗ Tuấn Kiệt',
          phone: '0912000006',
          password: passwordHash,
          avatar: null,
          provider: 'local',
          provider_id: null,
          role_id: 3,
          status: 'active',
          email_verified_at: '2026-04-02 09:25:00',
        },
        {
          id: 12,
          email: 'customer07@example.com',
          name: 'Bùi Ngọc Mai',
          phone: '0912000007',
          password: passwordHash,
          avatar: null,
          provider: 'local',
          provider_id: null,
          role_id: 3,
          status: 'active',
          email_verified_at: '2026-04-02 09:30:00',
        },
        {
          id: 13,
          email: 'customer08@example.com',
          name: 'Hoàng Đức Nam',
          phone: '0912000008',
          password: passwordHash,
          avatar: null,
          provider: 'local',
          provider_id: null,
          role_id: 3,
          status: 'active',
          email_verified_at: '2026-04-02 09:35:00',
        },
        {
          id: 14,
          email: 'customer09@example.com',
          name: 'Đặng Thảo Nhi',
          phone: '0912000009',
          password: passwordHash,
          avatar: null,
          provider: 'local',
          provider_id: null,
          role_id: 3,
          status: 'active',
          email_verified_at: '2026-04-02 09:40:00',
        },
        {
          id: 15,
          email: 'customer10@example.com',
          name: 'Cao Minh Quân',
          phone: '0912000010',
          password: passwordHash,
          avatar: null,
          provider: 'local',
          provider_id: null,
          role_id: 3,
          status: 'active',
          email_verified_at: '2026-04-02 09:45:00',
        },
        {
          id: 16,
          email: 'customer11@example.com',
          name: 'Ngô Bảo Trâm',
          phone: '0912000011',
          password: passwordHash,
          avatar: null,
          provider: 'local',
          provider_id: null,
          role_id: 3,
          status: 'active',
          email_verified_at: '2026-04-02 09:50:00',
        },
        {
          id: 17,
          email: 'customer12@example.com',
          name: 'Dương Anh Tú',
          phone: '0912000012',
          password: passwordHash,
          avatar: null,
          provider: 'local',
          provider_id: null,
          role_id: 3,
          status: 'active',
          email_verified_at: '2026-04-02 09:55:00',
        },
        {
          id: 18,
          email: 'customer13@example.com',
          name: 'Mai Thanh Vy',
          phone: '0912000013',
          password: passwordHash,
          avatar: null,
          provider: 'local',
          provider_id: null,
          role_id: 3,
          status: 'inactive',
          email_verified_at: null,
        },
        {
          id: 19,
          email: 'customer14@example.com',
          name: 'Tạ Hữu Phúc',
          phone: '0912000014',
          password: passwordHash,
          avatar: null,
          provider: 'local',
          provider_id: null,
          role_id: 3,
          status: 'blocked',
          email_verified_at: null,
        },
        {
          id: 20,
          email: 'customer15@example.com',
          name: 'Hồ Ngọc Hà',
          phone: '0912000015',
          password: passwordHash,
          avatar: null,
          provider: 'local',
          provider_id: null,
          role_id: 3,
          status: 'active',
          email_verified_at: '2026-04-02 10:00:00',
        },
      ],
    );

    await this.insertRows(
      queryRunner,
      'refresh_tokens',
      ['id', 'user_id', 'token', 'expires_at', 'revoked_at'],
      [
        {
          id: 1,
          user_id: 1,
          token: 'sample-refresh-token-admin-001',
          expires_at: '2026-05-07 00:00:00',
          revoked_at: null,
        },
        {
          id: 2,
          user_id: 2,
          token: 'sample-refresh-token-staff-001',
          expires_at: '2026-05-07 00:00:00',
          revoked_at: null,
        },
        {
          id: 3,
          user_id: 3,
          token: 'sample-refresh-token-member-001',
          expires_at: '2026-05-07 00:00:00',
          revoked_at: null,
        },
        {
          id: 4,
          user_id: 3,
          token: 'sample-refresh-token-member-revoked-001',
          expires_at: '2026-05-07 00:00:00',
          revoked_at: '2026-04-30 10:00:00',
        },
      ],
    );

    await this.insertRows(
      queryRunner,
      'categories',
      ['id', 'name', 'slug', 'description', 'image', 'parent_id', 'is_active'],
      [
        {
          id: 1,
          name: 'Điện thoại',
          slug: 'dien-thoai',
          description: 'Điện thoại thông minh và phụ kiện liên quan',
          image: 'categories/dien-thoai.jpg',
          parent_id: null,
          is_active: true,
        },
        {
          id: 2,
          name: 'Laptop',
          slug: 'laptop',
          description: 'Laptop học tập, văn phòng và gaming',
          image: 'categories/laptop.jpg',
          parent_id: null,
          is_active: true,
        },
        {
          id: 3,
          name: 'Máy tính bảng',
          slug: 'may-tinh-bang',
          description: 'Tablet iOS và Android',
          image: 'categories/tablet.jpg',
          parent_id: null,
          is_active: true,
        },
        {
          id: 4,
          name: 'Tai nghe',
          slug: 'tai-nghe',
          description: 'Tai nghe có dây, bluetooth và chống ồn',
          image: 'categories/tai-nghe.jpg',
          parent_id: null,
          is_active: true,
        },
        {
          id: 5,
          name: 'Đồng hồ thông minh',
          slug: 'dong-ho-thong-minh',
          description: 'Thiết bị đeo thông minh',
          image: 'categories/smartwatch.jpg',
          parent_id: null,
          is_active: true,
        },
        {
          id: 6,
          name: 'Phụ kiện',
          slug: 'phu-kien',
          description: 'Ốp lưng, cáp sạc, sạc nhanh và kính cường lực',
          image: 'categories/phu-kien.jpg',
          parent_id: null,
          is_active: true,
        },
        {
          id: 7,
          name: 'Màn hình',
          slug: 'man-hinh',
          description: 'Màn hình văn phòng, đồ họa và gaming',
          image: 'categories/man-hinh.jpg',
          parent_id: null,
          is_active: true,
        },
        {
          id: 8,
          name: 'Bàn phím',
          slug: 'ban-phim',
          description: 'Bàn phím cơ và bàn phím văn phòng',
          image: 'categories/ban-phim.jpg',
          parent_id: null,
          is_active: true,
        },
        {
          id: 9,
          name: 'Chuột máy tính',
          slug: 'chuot-may-tinh',
          description: 'Chuột văn phòng và chuột gaming',
          image: 'categories/chuot.jpg',
          parent_id: null,
          is_active: true,
        },
        {
          id: 10,
          name: 'Loa',
          slug: 'loa',
          description: 'Loa bluetooth và loa máy tính',
          image: 'categories/loa.jpg',
          parent_id: null,
          is_active: true,
        },
        {
          id: 11,
          name: 'Thiết bị mạng',
          slug: 'thiet-bi-mang',
          description: 'Router, modem và thiết bị mở rộng sóng',
          image: 'categories/network.jpg',
          parent_id: null,
          is_active: true,
        },
        {
          id: 12,
          name: 'Lưu trữ',
          slug: 'luu-tru',
          description: 'SSD, HDD, USB và thẻ nhớ',
          image: 'categories/storage.jpg',
          parent_id: null,
          is_active: true,
        },
        {
          id: 13,
          name: 'Máy in',
          slug: 'may-in',
          description: 'Máy in gia đình và văn phòng',
          image: 'categories/may-in.jpg',
          parent_id: null,
          is_active: true,
        },
        {
          id: 14,
          name: 'Camera an ninh',
          slug: 'camera-an-ninh',
          description: 'Camera giám sát trong nhà và ngoài trời',
          image: 'categories/camera.jpg',
          parent_id: null,
          is_active: true,
        },
        {
          id: 15,
          name: 'Danh mục tạm ẩn',
          slug: 'danh-muc-tam-an',
          description: 'Danh mục mẫu đang tạm ngưng',
          image: null,
          parent_id: null,
          is_active: false,
        },
      ],
    );

    await this.insertRows(
      queryRunner,
      'products',
      [
        'id',
        'category_id',
        'name',
        'slug',
        'sku',
        'price',
        'sale_price',
        'quantity',
        'short_description',
        'description',
        'thumbnail',
        'status',
      ],
      [
        {
          id: 1,
          category_id: 1,
          name: 'iPhone 15 128GB',
          slug: 'iphone-15-128gb',
          sku: 'IP15-128-BLK',
          price: 22990000,
          sale_price: 21490000,
          quantity: 45,
          short_description: 'iPhone 15 chính hãng 128GB',
          description:
            'Màn hình Super Retina XDR, chip A16 Bionic, camera 48MP.',
          thumbnail: 'products/iphone-15.jpg',
          status: 'active',
        },
        {
          id: 2,
          category_id: 1,
          name: 'Samsung Galaxy S24',
          slug: 'samsung-galaxy-s24',
          sku: 'SS-S24-256',
          price: 20990000,
          sale_price: 19990000,
          quantity: 38,
          short_description: 'Galaxy S24 hiệu năng cao',
          description: 'Điện thoại Samsung Galaxy S24 hỗ trợ Galaxy AI.',
          thumbnail: 'products/galaxy-s24.jpg',
          status: 'active',
        },
        {
          id: 3,
          category_id: 1,
          name: 'Xiaomi 14',
          slug: 'xiaomi-14',
          sku: 'XIAOMI-14',
          price: 17990000,
          sale_price: 16990000,
          quantity: 24,
          short_description: 'Flagship Xiaomi camera Leica',
          description: 'Thiết kế nhỏ gọn, hiệu năng cao, sạc nhanh.',
          thumbnail: 'products/xiaomi-14.jpg',
          status: 'active',
        },
        {
          id: 4,
          category_id: 2,
          name: 'MacBook Air M2 13 inch',
          slug: 'macbook-air-m2-13',
          sku: 'MBA-M2-13',
          price: 25990000,
          sale_price: 23990000,
          quantity: 20,
          short_description: 'Laptop Apple M2 mỏng nhẹ',
          description: 'MacBook Air M2 phù hợp học tập và văn phòng.',
          thumbnail: 'products/macbook-air-m2.jpg',
          status: 'active',
        },
        {
          id: 5,
          category_id: 2,
          name: 'Dell XPS 13 Plus',
          slug: 'dell-xps-13-plus',
          sku: 'DELL-XPS13P',
          price: 32990000,
          sale_price: 30990000,
          quantity: 12,
          short_description: 'Laptop cao cấp Dell XPS',
          description: 'Thiết kế mỏng nhẹ, màn hình đẹp, hiệu năng ổn định.',
          thumbnail: 'products/dell-xps-13.jpg',
          status: 'active',
        },
        {
          id: 6,
          category_id: 2,
          name: 'ASUS TUF Gaming F15',
          slug: 'asus-tuf-gaming-f15',
          sku: 'ASUS-TUF-F15',
          price: 23990000,
          sale_price: 21990000,
          quantity: 16,
          short_description: 'Laptop gaming phổ thông',
          description:
            'Card đồ họa rời, tản nhiệt tốt, màn hình tần số quét cao.',
          thumbnail: 'products/asus-tuf-f15.jpg',
          status: 'active',
        },
        {
          id: 7,
          category_id: 3,
          name: 'iPad Air 5 WiFi',
          slug: 'ipad-air-5-wifi',
          sku: 'IPAD-AIR5-WIFI',
          price: 15990000,
          sale_price: 14990000,
          quantity: 30,
          short_description: 'iPad Air 5 chip M1',
          description: 'Máy tính bảng phù hợp học tập, ghi chú và giải trí.',
          thumbnail: 'products/ipad-air-5.jpg',
          status: 'active',
        },
        {
          id: 8,
          category_id: 3,
          name: 'Samsung Galaxy Tab S9',
          slug: 'galaxy-tab-s9',
          sku: 'TAB-S9',
          price: 18990000,
          sale_price: 17990000,
          quantity: 18,
          short_description: 'Tablet Android cao cấp',
          description: 'Màn hình AMOLED, bút S Pen, chống nước.',
          thumbnail: 'products/tab-s9.jpg',
          status: 'active',
        },
        {
          id: 9,
          category_id: 4,
          name: 'AirPods Pro 2',
          slug: 'airpods-pro-2',
          sku: 'AIRPODS-PRO2',
          price: 6490000,
          sale_price: 5890000,
          quantity: 60,
          short_description: 'Tai nghe chống ồn Apple',
          description: 'Chống ồn chủ động, xuyên âm, hộp sạc MagSafe.',
          thumbnail: 'products/airpods-pro-2.jpg',
          status: 'active',
        },
        {
          id: 10,
          category_id: 4,
          name: 'Sony WH-1000XM5',
          slug: 'sony-wh-1000xm5',
          sku: 'SONY-XM5',
          price: 8990000,
          sale_price: 7990000,
          quantity: 25,
          short_description: 'Tai nghe chống ồn Sony',
          description: 'Chất âm tốt, chống ồn mạnh, pin lâu.',
          thumbnail: 'products/sony-xm5.jpg',
          status: 'active',
        },
        {
          id: 11,
          category_id: 5,
          name: 'Apple Watch Series 9',
          slug: 'apple-watch-series-9',
          sku: 'AW-S9-45',
          price: 10490000,
          sale_price: 9990000,
          quantity: 22,
          short_description: 'Đồng hồ thông minh Apple',
          description: 'Theo dõi sức khỏe, tập luyện và thông báo.',
          thumbnail: 'products/apple-watch-s9.jpg',
          status: 'active',
        },
        {
          id: 12,
          category_id: 5,
          name: 'Samsung Galaxy Watch 6',
          slug: 'galaxy-watch-6',
          sku: 'GWATCH-6',
          price: 6990000,
          sale_price: 6290000,
          quantity: 27,
          short_description: 'Smartwatch Samsung',
          description: 'Theo dõi sức khỏe và kết nối hệ sinh thái Galaxy.',
          thumbnail: 'products/galaxy-watch-6.jpg',
          status: 'active',
        },
        {
          id: 13,
          category_id: 6,
          name: 'Sạc nhanh Anker 65W',
          slug: 'sac-nhanh-anker-65w',
          sku: 'ANKER-65W',
          price: 990000,
          sale_price: 850000,
          quantity: 90,
          short_description: 'Củ sạc nhanh đa cổng',
          description: 'Sạc nhanh laptop, điện thoại và tablet.',
          thumbnail: 'products/anker-65w.jpg',
          status: 'active',
        },
        {
          id: 14,
          category_id: 7,
          name: 'LG UltraGear 27 inch 144Hz',
          slug: 'lg-ultragear-27-144hz',
          sku: 'LG-UG-27-144',
          price: 5990000,
          sale_price: 5490000,
          quantity: 15,
          short_description: 'Màn hình gaming 144Hz',
          description: 'Tấm nền IPS, tốc độ phản hồi nhanh.',
          thumbnail: 'products/lg-ultragear.jpg',
          status: 'active',
        },
        {
          id: 15,
          category_id: 8,
          name: 'Keychron K2 V2',
          slug: 'keychron-k2-v2',
          sku: 'KEY-K2V2',
          price: 2190000,
          sale_price: 1990000,
          quantity: 35,
          short_description: 'Bàn phím cơ không dây',
          description: 'Layout 75%, kết nối Bluetooth và USB-C.',
          thumbnail: 'products/keychron-k2.jpg',
          status: 'active',
        },
        {
          id: 16,
          category_id: 9,
          name: 'Logitech MX Master 3S',
          slug: 'logitech-mx-master-3s',
          sku: 'LOGI-MX3S',
          price: 2590000,
          sale_price: 2290000,
          quantity: 40,
          short_description: 'Chuột văn phòng cao cấp',
          description: 'Cảm biến chính xác, cuộn MagSpeed, pin lâu.',
          thumbnail: 'products/mx-master-3s.jpg',
          status: 'active',
        },
        {
          id: 17,
          category_id: 10,
          name: 'JBL Flip 6',
          slug: 'jbl-flip-6',
          sku: 'JBL-FLIP6',
          price: 2990000,
          sale_price: 2690000,
          quantity: 31,
          short_description: 'Loa bluetooth chống nước',
          description: 'Âm thanh mạnh mẽ, pin lâu, chống nước IP67.',
          thumbnail: 'products/jbl-flip-6.jpg',
          status: 'active',
        },
        {
          id: 18,
          category_id: 11,
          name: 'TP-Link Archer AX55',
          slug: 'tp-link-archer-ax55',
          sku: 'TPLINK-AX55',
          price: 2390000,
          sale_price: 2190000,
          quantity: 28,
          short_description: 'Router WiFi 6',
          description: 'Tốc độ cao, vùng phủ rộng, nhiều thiết bị.',
          thumbnail: 'products/tplink-ax55.jpg',
          status: 'active',
        },
        {
          id: 19,
          category_id: 12,
          name: 'Samsung SSD 980 1TB',
          slug: 'samsung-ssd-980-1tb',
          sku: 'SSD-980-1TB',
          price: 1890000,
          sale_price: 1690000,
          quantity: 0,
          short_description: 'SSD NVMe 1TB',
          description: 'Tốc độ đọc ghi cao, phù hợp nâng cấp máy tính.',
          thumbnail: 'products/ssd-980.jpg',
          status: 'out_of_stock',
        },
        {
          id: 20,
          category_id: 13,
          name: 'Canon LBP 2900',
          slug: 'canon-lbp-2900',
          sku: 'CANON-LBP2900',
          price: 3990000,
          sale_price: null,
          quantity: 0,
          short_description: 'Máy in laser phổ thông',
          description: 'Máy in văn phòng phổ biến, đã tạm ngừng bán.',
          thumbnail: 'products/canon-lbp2900.jpg',
          status: 'inactive',
        },
      ],
    );

    await this.insertRows(
      queryRunner,
      'product_images',
      ['id', 'product_id', 'image_url', 'sort_order', 'is_primary'],
      Array.from({ length: 20 }, (_, index) => ({
        id: index + 1,
        product_id: index + 1,
        image_url: `products/sample-${index + 1}.jpg`,
        sort_order: 1,
        is_primary: true,
      })),
    );

    await this.insertRows(
      queryRunner,
      'addresses',
      [
        'id',
        'user_id',
        'receiver_name',
        'receiver_phone',
        'province',
        'district',
        'ward',
        'address_detail',
        'is_default',
      ],
      [
        {
          id: 1,
          user_id: 6,
          receiver_name: 'Nguyễn Minh Anh',
          receiver_phone: '0912000001',
          province: 'Hà Nội',
          district: 'Cầu Giấy',
          ward: 'Dịch Vọng',
          address_detail: 'Số 12 ngõ 88 Trần Thái Tông',
          is_default: true,
        },
        {
          id: 2,
          user_id: 7,
          receiver_name: 'Trần Quốc Bảo',
          receiver_phone: '0912000002',
          province: 'Hà Nội',
          district: 'Đống Đa',
          ward: 'Láng Hạ',
          address_detail: 'Số 25 Thái Hà',
          is_default: true,
        },
        {
          id: 3,
          user_id: 8,
          receiver_name: 'Lê Hoàng Chi',
          receiver_phone: '0912000003',
          province: 'TP. Hồ Chí Minh',
          district: 'Quận 1',
          ward: 'Bến Nghé',
          address_detail: 'Số 10 Nguyễn Huệ',
          is_default: true,
        },
        {
          id: 4,
          user_id: 9,
          receiver_name: 'Phạm Gia Huy',
          receiver_phone: '0912000004',
          province: 'Đà Nẵng',
          district: 'Hải Châu',
          ward: 'Hải Châu 1',
          address_detail: 'Số 56 Bạch Đằng',
          is_default: true,
        },
        {
          id: 5,
          user_id: 10,
          receiver_name: 'Vũ Khánh Linh',
          receiver_phone: '0912000005',
          province: 'Hải Phòng',
          district: 'Ngô Quyền',
          ward: 'Máy Tơ',
          address_detail: 'Số 18 Lạch Tray',
          is_default: true,
        },
        {
          id: 6,
          user_id: 11,
          receiver_name: 'Đỗ Tuấn Kiệt',
          receiver_phone: '0912000006',
          province: 'Ninh Bình',
          district: 'Hoa Lư',
          ward: 'Ninh Hải',
          address_detail: 'Thôn Văn Lâm',
          is_default: true,
        },
        {
          id: 7,
          user_id: 12,
          receiver_name: 'Bùi Ngọc Mai',
          receiver_phone: '0912000007',
          province: 'Bắc Ninh',
          district: 'Từ Sơn',
          ward: 'Đình Bảng',
          address_detail: 'Khu phố Chùa Dận',
          is_default: true,
        },
        {
          id: 8,
          user_id: 13,
          receiver_name: 'Hoàng Đức Nam',
          receiver_phone: '0912000008',
          province: 'Nam Định',
          district: 'Mỹ Lộc',
          ward: 'Mỹ Hưng',
          address_detail: 'Xóm 4',
          is_default: true,
        },
        {
          id: 9,
          user_id: 14,
          receiver_name: 'Đặng Thảo Nhi',
          receiver_phone: '0912000009',
          province: 'Thanh Hóa',
          district: 'Sầm Sơn',
          ward: 'Trường Sơn',
          address_detail: 'Số 7 Hồ Xuân Hương',
          is_default: true,
        },
        {
          id: 10,
          user_id: 15,
          receiver_name: 'Cao Minh Quân',
          receiver_phone: '0912000010',
          province: 'Nghệ An',
          district: 'Vinh',
          ward: 'Hưng Bình',
          address_detail: 'Số 90 Lê Lợi',
          is_default: true,
        },
        {
          id: 11,
          user_id: 16,
          receiver_name: 'Ngô Bảo Trâm',
          receiver_phone: '0912000011',
          province: 'Huế',
          district: 'Thuận Hóa',
          ward: 'Phú Hội',
          address_detail: 'Số 15 Hùng Vương',
          is_default: true,
        },
        {
          id: 12,
          user_id: 17,
          receiver_name: 'Dương Anh Tú',
          receiver_phone: '0912000012',
          province: 'Cần Thơ',
          district: 'Ninh Kiều',
          ward: 'An Khánh',
          address_detail: 'Số 101 Nguyễn Văn Cừ',
          is_default: true,
        },
        {
          id: 13,
          user_id: 18,
          receiver_name: 'Mai Thanh Vy',
          receiver_phone: '0912000013',
          province: 'Quảng Ninh',
          district: 'Hạ Long',
          ward: 'Bãi Cháy',
          address_detail: 'Số 3 Hạ Long',
          is_default: true,
        },
        {
          id: 14,
          user_id: 19,
          receiver_name: 'Tạ Hữu Phúc',
          receiver_phone: '0912000014',
          province: 'Bình Dương',
          district: 'Thủ Dầu Một',
          ward: 'Phú Cường',
          address_detail: 'Số 22 Đại lộ Bình Dương',
          is_default: true,
        },
        {
          id: 15,
          user_id: 20,
          receiver_name: 'Hồ Ngọc Hà',
          receiver_phone: '0912000015',
          province: 'Đồng Nai',
          district: 'Biên Hòa',
          ward: 'Tân Phong',
          address_detail: 'Số 9 Đồng Khởi',
          is_default: true,
        },
      ],
    );

    await this.insertRows(
      queryRunner,
      'carts',
      ['id', 'user_id'],
      [
        { id: 1, user_id: 6 },
        { id: 2, user_id: 7 },
        { id: 3, user_id: 8 },
        { id: 4, user_id: 9 },
        { id: 5, user_id: 10 },
        { id: 6, user_id: 11 },
        { id: 7, user_id: 12 },
        { id: 8, user_id: 13 },
        { id: 9, user_id: 14 },
        { id: 10, user_id: 15 },
        { id: 11, user_id: 16 },
        { id: 12, user_id: 17 },
        { id: 13, user_id: 18 },
        { id: 14, user_id: 19 },
        { id: 15, user_id: 20 },
      ],
    );

    await this.insertRows(
      queryRunner,
      'cart_items',
      ['id', 'cart_id', 'product_id', 'quantity', 'price'],
      [
        { id: 1, cart_id: 1, product_id: 1, quantity: 1, price: 21490000 },
        { id: 2, cart_id: 1, product_id: 9, quantity: 1, price: 5890000 },
        { id: 3, cart_id: 2, product_id: 2, quantity: 1, price: 19990000 },
        { id: 4, cart_id: 3, product_id: 4, quantity: 1, price: 23990000 },
        { id: 5, cart_id: 4, product_id: 13, quantity: 2, price: 850000 },
        { id: 6, cart_id: 5, product_id: 15, quantity: 1, price: 1990000 },
        { id: 7, cart_id: 6, product_id: 16, quantity: 1, price: 2290000 },
        { id: 8, cart_id: 7, product_id: 17, quantity: 1, price: 2690000 },
        { id: 9, cart_id: 8, product_id: 18, quantity: 1, price: 2190000 },
        { id: 10, cart_id: 9, product_id: 10, quantity: 1, price: 7990000 },
        { id: 11, cart_id: 10, product_id: 7, quantity: 1, price: 14990000 },
        { id: 12, cart_id: 11, product_id: 8, quantity: 1, price: 17990000 },
        { id: 13, cart_id: 12, product_id: 11, quantity: 1, price: 9990000 },
        { id: 14, cart_id: 13, product_id: 12, quantity: 1, price: 6290000 },
        { id: 15, cart_id: 14, product_id: 14, quantity: 1, price: 5490000 },
        { id: 16, cart_id: 15, product_id: 3, quantity: 1, price: 16990000 },
        { id: 17, cart_id: 2, product_id: 13, quantity: 1, price: 850000 },
        { id: 18, cart_id: 3, product_id: 16, quantity: 1, price: 2290000 },
        { id: 19, cart_id: 4, product_id: 9, quantity: 1, price: 5890000 },
        { id: 20, cart_id: 5, product_id: 18, quantity: 1, price: 2190000 },
      ],
    );

    await this.insertRows(
      queryRunner,
      'coupons',
      [
        'id',
        'code',
        'type',
        'value',
        'min_order_amount',
        'max_discount_amount',
        'usage_limit',
        'used_count',
        'start_date',
        'end_date',
        'is_active',
      ],
      [
        {
          id: 1,
          code: 'WELCOME10',
          type: 'percent',
          value: 10,
          min_order_amount: 500000,
          max_discount_amount: 300000,
          usage_limit: 200,
          used_count: 15,
          start_date: '2026-04-01 00:00:00',
          end_date: '2026-12-31 23:59:59',
          is_active: true,
        },
        {
          id: 2,
          code: 'FREESHIP',
          type: 'free_shipping',
          value: 0,
          min_order_amount: 300000,
          max_discount_amount: 50000,
          usage_limit: 300,
          used_count: 21,
          start_date: '2026-04-01 00:00:00',
          end_date: '2026-12-31 23:59:59',
          is_active: true,
        },
        {
          id: 3,
          code: 'SALE500K',
          type: 'fixed',
          value: 500000,
          min_order_amount: 5000000,
          max_discount_amount: null,
          usage_limit: 100,
          used_count: 7,
          start_date: '2026-04-01 00:00:00',
          end_date: '2026-09-30 23:59:59',
          is_active: true,
        },
        {
          id: 4,
          code: 'LAPTOP5',
          type: 'percent',
          value: 5,
          min_order_amount: 10000000,
          max_discount_amount: 1000000,
          usage_limit: 80,
          used_count: 4,
          start_date: '2026-04-01 00:00:00',
          end_date: '2026-08-31 23:59:59',
          is_active: true,
        },
        {
          id: 5,
          code: 'PHONE300',
          type: 'fixed',
          value: 300000,
          min_order_amount: 3000000,
          max_discount_amount: null,
          usage_limit: 120,
          used_count: 11,
          start_date: '2026-04-01 00:00:00',
          end_date: '2026-10-31 23:59:59',
          is_active: true,
        },
        {
          id: 6,
          code: 'APRIL20',
          type: 'percent',
          value: 20,
          min_order_amount: 2000000,
          max_discount_amount: 700000,
          usage_limit: 50,
          used_count: 50,
          start_date: '2026-04-01 00:00:00',
          end_date: '2026-04-30 23:59:59',
          is_active: true,
        },
        {
          id: 7,
          code: 'OLD2025',
          type: 'fixed',
          value: 200000,
          min_order_amount: 1000000,
          max_discount_amount: null,
          usage_limit: 100,
          used_count: 99,
          start_date: '2025-01-01 00:00:00',
          end_date: '2025-12-31 23:59:59',
          is_active: false,
        },
        {
          id: 8,
          code: 'VIP15',
          type: 'percent',
          value: 15,
          min_order_amount: 10000000,
          max_discount_amount: 1500000,
          usage_limit: 40,
          used_count: 3,
          start_date: '2026-04-01 00:00:00',
          end_date: '2026-12-31 23:59:59',
          is_active: true,
        },
        {
          id: 9,
          code: 'NEWUSER',
          type: 'fixed',
          value: 150000,
          min_order_amount: 800000,
          max_discount_amount: null,
          usage_limit: 500,
          used_count: 31,
          start_date: '2026-04-01 00:00:00',
          end_date: '2026-12-31 23:59:59',
          is_active: true,
        },
        {
          id: 10,
          code: 'TECHDAY',
          type: 'percent',
          value: 7,
          min_order_amount: 1000000,
          max_discount_amount: 400000,
          usage_limit: 150,
          used_count: 8,
          start_date: '2026-04-01 00:00:00',
          end_date: '2026-07-31 23:59:59',
          is_active: true,
        },
      ],
    );

    await this.insertRows(
      queryRunner,
      'orders',
      [
        'id',
        'user_id',
        'coupon_id',
        'order_code',
        'customer_name',
        'customer_phone',
        'customer_email',
        'shipping_address',
        'note',
        'subtotal',
        'shipping_fee',
        'discount_amount',
        'total_amount',
        'payment_method',
        'payment_status',
        'order_status',
      ],
      [
        {
          id: 1,
          user_id: 6,
          coupon_id: 1,
          order_code: 'ORD-202604-0001',
          customer_name: 'Nguyễn Minh Anh',
          customer_phone: '0912000001',
          customer_email: 'customer01@example.com',
          shipping_address: 'Số 12 ngõ 88 Trần Thái Tông, Cầu Giấy, Hà Nội',
          note: 'Giao giờ hành chính',
          subtotal: 21490000,
          shipping_fee: 30000,
          discount_amount: 300000,
          total_amount: 21220000,
          payment_method: 'vnpay',
          payment_status: 'paid',
          order_status: 'completed',
        },
        {
          id: 2,
          user_id: 7,
          coupon_id: 2,
          order_code: 'ORD-202604-0002',
          customer_name: 'Trần Quốc Bảo',
          customer_phone: '0912000002',
          customer_email: 'customer02@example.com',
          shipping_address: 'Số 25 Thái Hà, Đống Đa, Hà Nội',
          note: null,
          subtotal: 19990000,
          shipping_fee: 0,
          discount_amount: 30000,
          total_amount: 19960000,
          payment_method: 'cod',
          payment_status: 'unpaid',
          order_status: 'shipping',
        },
        {
          id: 3,
          user_id: 8,
          coupon_id: 3,
          order_code: 'ORD-202604-0003',
          customer_name: 'Lê Hoàng Chi',
          customer_phone: '0912000003',
          customer_email: 'customer03@example.com',
          shipping_address: 'Số 10 Nguyễn Huệ, Quận 1, TP. Hồ Chí Minh',
          note: 'Gọi trước khi giao',
          subtotal: 23990000,
          shipping_fee: 40000,
          discount_amount: 500000,
          total_amount: 23530000,
          payment_method: 'bank_transfer',
          payment_status: 'paid',
          order_status: 'completed',
        },
        {
          id: 4,
          user_id: 9,
          coupon_id: null,
          order_code: 'ORD-202604-0004',
          customer_name: 'Phạm Gia Huy',
          customer_phone: '0912000004',
          customer_email: 'customer04@example.com',
          shipping_address: 'Số 56 Bạch Đằng, Hải Châu, Đà Nẵng',
          note: null,
          subtotal: 7590000,
          shipping_fee: 30000,
          discount_amount: 0,
          total_amount: 7620000,
          payment_method: 'cod',
          payment_status: 'unpaid',
          order_status: 'pending',
        },
        {
          id: 5,
          user_id: 10,
          coupon_id: 5,
          order_code: 'ORD-202604-0005',
          customer_name: 'Vũ Khánh Linh',
          customer_phone: '0912000005',
          customer_email: 'customer05@example.com',
          shipping_address: 'Số 18 Lạch Tray, Ngô Quyền, Hải Phòng',
          note: null,
          subtotal: 4180000,
          shipping_fee: 30000,
          discount_amount: 300000,
          total_amount: 3910000,
          payment_method: 'momo',
          payment_status: 'paid',
          order_status: 'confirmed',
        },
        {
          id: 6,
          user_id: 11,
          coupon_id: 9,
          order_code: 'ORD-202604-0006',
          customer_name: 'Đỗ Tuấn Kiệt',
          customer_phone: '0912000006',
          customer_email: 'customer06@example.com',
          shipping_address: 'Thôn Văn Lâm, Hoa Lư, Ninh Bình',
          note: null,
          subtotal: 2290000,
          shipping_fee: 30000,
          discount_amount: 150000,
          total_amount: 2170000,
          payment_method: 'cod',
          payment_status: 'unpaid',
          order_status: 'preparing',
        },
        {
          id: 7,
          user_id: 12,
          coupon_id: 10,
          order_code: 'ORD-202604-0007',
          customer_name: 'Bùi Ngọc Mai',
          customer_phone: '0912000007',
          customer_email: 'customer07@example.com',
          shipping_address: 'Khu phố Chùa Dận, Từ Sơn, Bắc Ninh',
          note: null,
          subtotal: 2690000,
          shipping_fee: 30000,
          discount_amount: 188300,
          total_amount: 2531700,
          payment_method: 'vnpay',
          payment_status: 'paid',
          order_status: 'completed',
        },
        {
          id: 8,
          user_id: 13,
          coupon_id: null,
          order_code: 'ORD-202604-0008',
          customer_name: 'Hoàng Đức Nam',
          customer_phone: '0912000008',
          customer_email: 'customer08@example.com',
          shipping_address: 'Xóm 4, Mỹ Lộc, Nam Định',
          note: 'Xuất hóa đơn điện tử',
          subtotal: 2190000,
          shipping_fee: 30000,
          discount_amount: 0,
          total_amount: 2220000,
          payment_method: 'paypal',
          payment_status: 'failed',
          order_status: 'cancelled',
        },
        {
          id: 9,
          user_id: 14,
          coupon_id: 8,
          order_code: 'ORD-202604-0009',
          customer_name: 'Đặng Thảo Nhi',
          customer_phone: '0912000009',
          customer_email: 'customer09@example.com',
          shipping_address: 'Số 7 Hồ Xuân Hương, Sầm Sơn, Thanh Hóa',
          note: null,
          subtotal: 7990000,
          shipping_fee: 30000,
          discount_amount: 1198500,
          total_amount: 6821500,
          payment_method: 'momo',
          payment_status: 'refunded',
          order_status: 'returned',
        },
        {
          id: 10,
          user_id: 15,
          coupon_id: 4,
          order_code: 'ORD-202604-0010',
          customer_name: 'Cao Minh Quân',
          customer_phone: '0912000010',
          customer_email: 'customer10@example.com',
          shipping_address: 'Số 90 Lê Lợi, Vinh, Nghệ An',
          note: null,
          subtotal: 14990000,
          shipping_fee: 30000,
          discount_amount: 749500,
          total_amount: 14270500,
          payment_method: 'bank_transfer',
          payment_status: 'paid',
          order_status: 'completed',
        },
        {
          id: 11,
          user_id: 16,
          coupon_id: 1,
          order_code: 'ORD-202604-0011',
          customer_name: 'Ngô Bảo Trâm',
          customer_phone: '0912000011',
          customer_email: 'customer11@example.com',
          shipping_address: 'Số 15 Hùng Vương, Huế',
          note: null,
          subtotal: 17990000,
          shipping_fee: 30000,
          discount_amount: 300000,
          total_amount: 17720000,
          payment_method: 'vnpay',
          payment_status: 'paid',
          order_status: 'shipping',
        },
        {
          id: 12,
          user_id: 17,
          coupon_id: null,
          order_code: 'ORD-202604-0012',
          customer_name: 'Dương Anh Tú',
          customer_phone: '0912000012',
          customer_email: 'customer12@example.com',
          shipping_address: 'Số 101 Nguyễn Văn Cừ, Cần Thơ',
          note: null,
          subtotal: 9990000,
          shipping_fee: 30000,
          discount_amount: 0,
          total_amount: 10020000,
          payment_method: 'cod',
          payment_status: 'unpaid',
          order_status: 'pending',
        },
        {
          id: 13,
          user_id: 18,
          coupon_id: null,
          order_code: 'ORD-202604-0013',
          customer_name: 'Mai Thanh Vy',
          customer_phone: '0912000013',
          customer_email: 'customer13@example.com',
          shipping_address: 'Số 3 Hạ Long, Quảng Ninh',
          note: null,
          subtotal: 6290000,
          shipping_fee: 30000,
          discount_amount: 0,
          total_amount: 6320000,
          payment_method: 'cod',
          payment_status: 'unpaid',
          order_status: 'confirmed',
        },
        {
          id: 14,
          user_id: 19,
          coupon_id: 6,
          order_code: 'ORD-202604-0014',
          customer_name: 'Tạ Hữu Phúc',
          customer_phone: '0912000014',
          customer_email: 'customer14@example.com',
          shipping_address: 'Số 22 Đại lộ Bình Dương, Bình Dương',
          note: null,
          subtotal: 5490000,
          shipping_fee: 30000,
          discount_amount: 700000,
          total_amount: 4820000,
          payment_method: 'momo',
          payment_status: 'paid',
          order_status: 'completed',
        },
        {
          id: 15,
          user_id: 20,
          coupon_id: 5,
          order_code: 'ORD-202604-0015',
          customer_name: 'Hồ Ngọc Hà',
          customer_phone: '0912000015',
          customer_email: 'customer15@example.com',
          shipping_address: 'Số 9 Đồng Khởi, Biên Hòa, Đồng Nai',
          note: 'Giao buổi tối',
          subtotal: 16990000,
          shipping_fee: 30000,
          discount_amount: 300000,
          total_amount: 16720000,
          payment_method: 'bank_transfer',
          payment_status: 'paid',
          order_status: 'completed',
        },
        {
          id: 16,
          user_id: 6,
          coupon_id: null,
          order_code: 'ORD-202604-0016',
          customer_name: 'Nguyễn Minh Anh',
          customer_phone: '0912000001',
          customer_email: 'customer01@example.com',
          shipping_address: 'Số 12 ngõ 88 Trần Thái Tông, Cầu Giấy, Hà Nội',
          note: null,
          subtotal: 5890000,
          shipping_fee: 30000,
          discount_amount: 0,
          total_amount: 5920000,
          payment_method: 'cod',
          payment_status: 'unpaid',
          order_status: 'preparing',
        },
        {
          id: 17,
          user_id: 7,
          coupon_id: 9,
          order_code: 'ORD-202604-0017',
          customer_name: 'Trần Quốc Bảo',
          customer_phone: '0912000002',
          customer_email: 'customer02@example.com',
          shipping_address: 'Số 25 Thái Hà, Đống Đa, Hà Nội',
          note: null,
          subtotal: 850000,
          shipping_fee: 30000,
          discount_amount: 150000,
          total_amount: 730000,
          payment_method: 'cod',
          payment_status: 'unpaid',
          order_status: 'cancelled',
        },
        {
          id: 18,
          user_id: 8,
          coupon_id: 2,
          order_code: 'ORD-202604-0018',
          customer_name: 'Lê Hoàng Chi',
          customer_phone: '0912000003',
          customer_email: 'customer03@example.com',
          shipping_address: 'Số 10 Nguyễn Huệ, Quận 1, TP. Hồ Chí Minh',
          note: null,
          subtotal: 2290000,
          shipping_fee: 0,
          discount_amount: 30000,
          total_amount: 2260000,
          payment_method: 'vnpay',
          payment_status: 'paid',
          order_status: 'completed',
        },
        {
          id: 19,
          user_id: 9,
          coupon_id: 10,
          order_code: 'ORD-202604-0019',
          customer_name: 'Phạm Gia Huy',
          customer_phone: '0912000004',
          customer_email: 'customer04@example.com',
          shipping_address: 'Số 56 Bạch Đằng, Hải Châu, Đà Nẵng',
          note: null,
          subtotal: 17990000,
          shipping_fee: 30000,
          discount_amount: 400000,
          total_amount: 17620000,
          payment_method: 'paypal',
          payment_status: 'failed',
          order_status: 'cancelled',
        },
        {
          id: 20,
          user_id: 10,
          coupon_id: 1,
          order_code: 'ORD-202604-0020',
          customer_name: 'Vũ Khánh Linh',
          customer_phone: '0912000005',
          customer_email: 'customer05@example.com',
          shipping_address: 'Số 18 Lạch Tray, Ngô Quyền, Hải Phòng',
          note: null,
          subtotal: 2690000,
          shipping_fee: 30000,
          discount_amount: 269000,
          total_amount: 2451000,
          payment_method: 'momo',
          payment_status: 'paid',
          order_status: 'completed',
        },
      ],
    );

    await this.insertRows(
      queryRunner,
      'order_items',
      [
        'id',
        'order_id',
        'product_id',
        'product_name',
        'product_image',
        'quantity',
        'price',
        'total',
      ],
      [
        {
          id: 1,
          order_id: 1,
          product_id: 1,
          product_name: 'iPhone 15 128GB',
          product_image: 'products/iphone-15.jpg',
          quantity: 1,
          price: 21490000,
          total: 21490000,
        },
        {
          id: 2,
          order_id: 2,
          product_id: 2,
          product_name: 'Samsung Galaxy S24',
          product_image: 'products/galaxy-s24.jpg',
          quantity: 1,
          price: 19990000,
          total: 19990000,
        },
        {
          id: 3,
          order_id: 3,
          product_id: 4,
          product_name: 'MacBook Air M2 13 inch',
          product_image: 'products/macbook-air-m2.jpg',
          quantity: 1,
          price: 23990000,
          total: 23990000,
        },
        {
          id: 4,
          order_id: 4,
          product_id: 13,
          product_name: 'Sạc nhanh Anker 65W',
          product_image: 'products/anker-65w.jpg',
          quantity: 2,
          price: 850000,
          total: 1700000,
        },
        {
          id: 5,
          order_id: 4,
          product_id: 9,
          product_name: 'AirPods Pro 2',
          product_image: 'products/airpods-pro-2.jpg',
          quantity: 1,
          price: 5890000,
          total: 5890000,
        },
        {
          id: 6,
          order_id: 5,
          product_id: 15,
          product_name: 'Keychron K2 V2',
          product_image: 'products/keychron-k2.jpg',
          quantity: 1,
          price: 1990000,
          total: 1990000,
        },
        {
          id: 7,
          order_id: 5,
          product_id: 18,
          product_name: 'TP-Link Archer AX55',
          product_image: 'products/tplink-ax55.jpg',
          quantity: 1,
          price: 2190000,
          total: 2190000,
        },
        {
          id: 8,
          order_id: 6,
          product_id: 16,
          product_name: 'Logitech MX Master 3S',
          product_image: 'products/mx-master-3s.jpg',
          quantity: 1,
          price: 2290000,
          total: 2290000,
        },
        {
          id: 9,
          order_id: 7,
          product_id: 17,
          product_name: 'JBL Flip 6',
          product_image: 'products/jbl-flip-6.jpg',
          quantity: 1,
          price: 2690000,
          total: 2690000,
        },
        {
          id: 10,
          order_id: 8,
          product_id: 18,
          product_name: 'TP-Link Archer AX55',
          product_image: 'products/tplink-ax55.jpg',
          quantity: 1,
          price: 2190000,
          total: 2190000,
        },
        {
          id: 11,
          order_id: 9,
          product_id: 10,
          product_name: 'Sony WH-1000XM5',
          product_image: 'products/sony-xm5.jpg',
          quantity: 1,
          price: 7990000,
          total: 7990000,
        },
        {
          id: 12,
          order_id: 10,
          product_id: 7,
          product_name: 'iPad Air 5 WiFi',
          product_image: 'products/ipad-air-5.jpg',
          quantity: 1,
          price: 14990000,
          total: 14990000,
        },
        {
          id: 13,
          order_id: 11,
          product_id: 8,
          product_name: 'Samsung Galaxy Tab S9',
          product_image: 'products/tab-s9.jpg',
          quantity: 1,
          price: 17990000,
          total: 17990000,
        },
        {
          id: 14,
          order_id: 12,
          product_id: 11,
          product_name: 'Apple Watch Series 9',
          product_image: 'products/apple-watch-s9.jpg',
          quantity: 1,
          price: 9990000,
          total: 9990000,
        },
        {
          id: 15,
          order_id: 13,
          product_id: 12,
          product_name: 'Samsung Galaxy Watch 6',
          product_image: 'products/galaxy-watch-6.jpg',
          quantity: 1,
          price: 6290000,
          total: 6290000,
        },
        {
          id: 16,
          order_id: 14,
          product_id: 14,
          product_name: 'LG UltraGear 27 inch 144Hz',
          product_image: 'products/lg-ultragear.jpg',
          quantity: 1,
          price: 5490000,
          total: 5490000,
        },
        {
          id: 17,
          order_id: 15,
          product_id: 3,
          product_name: 'Xiaomi 14',
          product_image: 'products/xiaomi-14.jpg',
          quantity: 1,
          price: 16990000,
          total: 16990000,
        },
        {
          id: 18,
          order_id: 16,
          product_id: 9,
          product_name: 'AirPods Pro 2',
          product_image: 'products/airpods-pro-2.jpg',
          quantity: 1,
          price: 5890000,
          total: 5890000,
        },
        {
          id: 19,
          order_id: 17,
          product_id: 13,
          product_name: 'Sạc nhanh Anker 65W',
          product_image: 'products/anker-65w.jpg',
          quantity: 1,
          price: 850000,
          total: 850000,
        },
        {
          id: 20,
          order_id: 18,
          product_id: 16,
          product_name: 'Logitech MX Master 3S',
          product_image: 'products/mx-master-3s.jpg',
          quantity: 1,
          price: 2290000,
          total: 2290000,
        },
        {
          id: 21,
          order_id: 19,
          product_id: 8,
          product_name: 'Samsung Galaxy Tab S9',
          product_image: 'products/tab-s9.jpg',
          quantity: 1,
          price: 17990000,
          total: 17990000,
        },
        {
          id: 22,
          order_id: 20,
          product_id: 17,
          product_name: 'JBL Flip 6',
          product_image: 'products/jbl-flip-6.jpg',
          quantity: 1,
          price: 2690000,
          total: 2690000,
        },
      ],
    );

    await this.insertRows(
      queryRunner,
      'payments',
      [
        'id',
        'order_id',
        'payment_method',
        'transaction_code',
        'amount',
        'status',
        'paid_at',
      ],
      [
        {
          id: 1,
          order_id: 1,
          payment_method: 'vnpay',
          transaction_code: 'VNP2026040001',
          amount: 21220000,
          status: 'paid',
          paid_at: '2026-04-05 10:01:00',
        },
        {
          id: 2,
          order_id: 2,
          payment_method: 'cod',
          transaction_code: null,
          amount: 19960000,
          status: 'unpaid',
          paid_at: null,
        },
        {
          id: 3,
          order_id: 3,
          payment_method: 'bank_transfer',
          transaction_code: 'BANK2026040003',
          amount: 23530000,
          status: 'paid',
          paid_at: '2026-04-06 11:00:00',
        },
        {
          id: 4,
          order_id: 4,
          payment_method: 'cod',
          transaction_code: null,
          amount: 7620000,
          status: 'unpaid',
          paid_at: null,
        },
        {
          id: 5,
          order_id: 5,
          payment_method: 'momo',
          transaction_code: 'MOMO2026040005',
          amount: 3910000,
          status: 'paid',
          paid_at: '2026-04-07 12:00:00',
        },
        {
          id: 6,
          order_id: 6,
          payment_method: 'cod',
          transaction_code: null,
          amount: 2170000,
          status: 'unpaid',
          paid_at: null,
        },
        {
          id: 7,
          order_id: 7,
          payment_method: 'vnpay',
          transaction_code: 'VNP2026040007',
          amount: 2531700,
          status: 'paid',
          paid_at: '2026-04-08 13:00:00',
        },
        {
          id: 8,
          order_id: 8,
          payment_method: 'paypal',
          transaction_code: 'PAYPAL_FAIL_0008',
          amount: 2220000,
          status: 'failed',
          paid_at: null,
        },
        {
          id: 9,
          order_id: 9,
          payment_method: 'momo',
          transaction_code: 'MOMO_REFUND_0009',
          amount: 6821500,
          status: 'refunded',
          paid_at: '2026-04-09 14:00:00',
        },
        {
          id: 10,
          order_id: 10,
          payment_method: 'bank_transfer',
          transaction_code: 'BANK2026040010',
          amount: 14270500,
          status: 'paid',
          paid_at: '2026-04-10 15:00:00',
        },
        {
          id: 11,
          order_id: 11,
          payment_method: 'vnpay',
          transaction_code: 'VNP2026040011',
          amount: 17720000,
          status: 'paid',
          paid_at: '2026-04-11 16:00:00',
        },
        {
          id: 12,
          order_id: 12,
          payment_method: 'cod',
          transaction_code: null,
          amount: 10020000,
          status: 'unpaid',
          paid_at: null,
        },
        {
          id: 13,
          order_id: 13,
          payment_method: 'cod',
          transaction_code: null,
          amount: 6320000,
          status: 'unpaid',
          paid_at: null,
        },
        {
          id: 14,
          order_id: 14,
          payment_method: 'momo',
          transaction_code: 'MOMO2026040014',
          amount: 4820000,
          status: 'paid',
          paid_at: '2026-04-14 17:00:00',
        },
        {
          id: 15,
          order_id: 15,
          payment_method: 'bank_transfer',
          transaction_code: 'BANK2026040015',
          amount: 16720000,
          status: 'paid',
          paid_at: '2026-04-15 18:00:00',
        },
        {
          id: 16,
          order_id: 16,
          payment_method: 'cod',
          transaction_code: null,
          amount: 5920000,
          status: 'unpaid',
          paid_at: null,
        },
        {
          id: 17,
          order_id: 17,
          payment_method: 'cod',
          transaction_code: null,
          amount: 730000,
          status: 'unpaid',
          paid_at: null,
        },
        {
          id: 18,
          order_id: 18,
          payment_method: 'vnpay',
          transaction_code: 'VNP2026040018',
          amount: 2260000,
          status: 'paid',
          paid_at: '2026-04-18 09:00:00',
        },
        {
          id: 19,
          order_id: 19,
          payment_method: 'paypal',
          transaction_code: 'PAYPAL_FAIL_0019',
          amount: 17620000,
          status: 'failed',
          paid_at: null,
        },
        {
          id: 20,
          order_id: 20,
          payment_method: 'momo',
          transaction_code: 'MOMO2026040020',
          amount: 2451000,
          status: 'paid',
          paid_at: '2026-04-20 09:00:00',
        },
      ],
    );

    await this.insertRows(
      queryRunner,
      'reviews',
      [
        'id',
        'user_id',
        'product_id',
        'order_id',
        'rating',
        'comment',
        'is_visible',
      ],
      [
        {
          id: 1,
          user_id: 6,
          product_id: 1,
          order_id: 1,
          rating: 5,
          comment: 'Sản phẩm đẹp, giao hàng nhanh.',
          is_visible: true,
        },
        {
          id: 2,
          user_id: 8,
          product_id: 4,
          order_id: 3,
          rating: 5,
          comment: 'Máy chạy mượt, pin tốt.',
          is_visible: true,
        },
        {
          id: 3,
          user_id: 12,
          product_id: 17,
          order_id: 7,
          rating: 4,
          comment: 'Loa nghe ổn, đóng gói kỹ.',
          is_visible: true,
        },
        {
          id: 4,
          user_id: 15,
          product_id: 7,
          order_id: 10,
          rating: 5,
          comment: 'Phù hợp học tập và ghi chú.',
          is_visible: true,
        },
        {
          id: 5,
          user_id: 19,
          product_id: 14,
          order_id: 14,
          rating: 4,
          comment: 'Màn hình đẹp, màu sắc ổn.',
          is_visible: true,
        },
        {
          id: 6,
          user_id: 20,
          product_id: 3,
          order_id: 15,
          rating: 5,
          comment: 'Máy nhỏ gọn, hiệu năng mạnh.',
          is_visible: true,
        },
        {
          id: 7,
          user_id: 8,
          product_id: 16,
          order_id: 18,
          rating: 4,
          comment: 'Chuột cầm chắc tay.',
          is_visible: true,
        },
        {
          id: 8,
          user_id: 10,
          product_id: 17,
          order_id: 20,
          rating: 5,
          comment: 'Âm thanh lớn, pin khá lâu.',
          is_visible: true,
        },
        {
          id: 9,
          user_id: 14,
          product_id: 10,
          order_id: 9,
          rating: 3,
          comment: 'Sản phẩm tốt nhưng đổi trả hơi lâu.',
          is_visible: true,
        },
        {
          id: 10,
          user_id: 7,
          product_id: 13,
          order_id: 17,
          rating: 2,
          comment: 'Đơn đã hủy nên đánh giá mẫu bị ẩn.',
          is_visible: false,
        },
      ],
    );

    await this.insertRows(
      queryRunner,
      'notifications',
      ['id', 'user_id', 'title', 'message', 'type', 'is_read'],
      [
        {
          id: 1,
          user_id: 6,
          title: 'Đơn hàng hoàn tất',
          message: 'Đơn ORD-202604-0001 đã hoàn tất.',
          type: 'order',
          is_read: true,
        },
        {
          id: 2,
          user_id: 7,
          title: 'Đơn đang giao',
          message: 'Đơn ORD-202604-0002 đang được giao.',
          type: 'order',
          is_read: false,
        },
        {
          id: 3,
          user_id: 8,
          title: 'Thanh toán thành công',
          message: 'Thanh toán đơn ORD-202604-0003 thành công.',
          type: 'payment',
          is_read: true,
        },
        {
          id: 4,
          user_id: 9,
          title: 'Đơn hàng mới',
          message: 'Đơn ORD-202604-0004 đang chờ xác nhận.',
          type: 'order',
          is_read: false,
        },
        {
          id: 5,
          user_id: 10,
          title: 'Khuyến mãi mới',
          message: 'Dùng mã WELCOME10 để giảm giá đơn hàng.',
          type: 'promotion',
          is_read: false,
        },
        {
          id: 6,
          user_id: null,
          title: 'Bảo trì hệ thống',
          message: 'Hệ thống sẽ bảo trì vào 23:00 tối nay.',
          type: 'system',
          is_read: false,
        },
        {
          id: 7,
          user_id: 1,
          title: 'Sản phẩm sắp hết hàng',
          message: 'MacBook Air M2 chỉ còn ít hàng.',
          type: 'inventory',
          is_read: false,
        },
        {
          id: 8,
          user_id: 2,
          title: 'Báo cáo ngày',
          message: 'Doanh thu ngày đã được cập nhật.',
          type: 'system',
          is_read: true,
        },
        {
          id: 9,
          user_id: 11,
          title: 'Đơn đang chuẩn bị',
          message: 'Đơn ORD-202604-0006 đang được chuẩn bị.',
          type: 'order',
          is_read: false,
        },
        {
          id: 10,
          user_id: 12,
          title: 'Cảm ơn đánh giá',
          message: 'Cảm ơn bạn đã đánh giá sản phẩm.',
          type: 'system',
          is_read: true,
        },
        {
          id: 11,
          user_id: 13,
          title: 'Thanh toán thất bại',
          message: 'Thanh toán đơn ORD-202604-0008 thất bại.',
          type: 'payment',
          is_read: false,
        },
        {
          id: 12,
          user_id: 14,
          title: 'Hoàn tiền',
          message: 'Đơn ORD-202604-0009 đã được hoàn tiền.',
          type: 'payment',
          is_read: false,
        },
        {
          id: 13,
          user_id: 15,
          title: 'Đơn hoàn tất',
          message: 'Đơn ORD-202604-0010 đã hoàn tất.',
          type: 'order',
          is_read: true,
        },
        {
          id: 14,
          user_id: 16,
          title: 'Đơn đang giao',
          message: 'Đơn ORD-202604-0011 đang giao.',
          type: 'order',
          is_read: false,
        },
        {
          id: 15,
          user_id: 17,
          title: 'Đơn chờ xác nhận',
          message: 'Đơn ORD-202604-0012 đang chờ xác nhận.',
          type: 'order',
          is_read: false,
        },
        {
          id: 16,
          user_id: 18,
          title: 'Tài khoản chưa xác minh',
          message: 'Vui lòng xác minh email để sử dụng đầy đủ chức năng.',
          type: 'system',
          is_read: false,
        },
        {
          id: 17,
          user_id: 19,
          title: 'Tài khoản bị khóa',
          message: 'Tài khoản của bạn đang bị khóa tạm thời.',
          type: 'system',
          is_read: false,
        },
        {
          id: 18,
          user_id: 20,
          title: 'Ưu đãi phụ kiện',
          message: 'Giảm giá phụ kiện trong tuần này.',
          type: 'promotion',
          is_read: false,
        },
        {
          id: 19,
          user_id: 3,
          title: 'Có đơn hàng mới',
          message: 'Có đơn hàng mới cần xử lý.',
          type: 'order',
          is_read: false,
        },
        {
          id: 20,
          user_id: 4,
          title: 'Yêu cầu hỗ trợ mới',
          message: 'Có liên hệ mới từ khách hàng.',
          type: 'system',
          is_read: false,
        },
      ],
    );

    await this.insertRows(
      queryRunner,
      'contacts',
      ['id', 'name', 'email', 'phone', 'subject', 'message', 'status'],
      [
        {
          id: 1,
          name: 'Nguyễn Minh Anh',
          email: 'customer01@example.com',
          phone: '0912000001',
          subject: 'Hỏi về bảo hành',
          message: 'Sản phẩm iPhone được bảo hành bao lâu?',
          status: 'resolved',
        },
        {
          id: 2,
          name: 'Trần Quốc Bảo',
          email: 'customer02@example.com',
          phone: '0912000002',
          subject: 'Đổi địa chỉ giao hàng',
          message: 'Tôi muốn đổi địa chỉ giao đơn hàng.',
          status: 'processing',
        },
        {
          id: 3,
          name: 'Lê Hoàng Chi',
          email: 'customer03@example.com',
          phone: '0912000003',
          subject: 'Xuất hóa đơn',
          message: 'Tôi cần xuất hóa đơn VAT.',
          status: 'new',
        },
        {
          id: 4,
          name: 'Phạm Gia Huy',
          email: 'customer04@example.com',
          phone: '0912000004',
          subject: 'Tư vấn sản phẩm',
          message: 'Tư vấn laptop học lập trình.',
          status: 'new',
        },
        {
          id: 5,
          name: 'Vũ Khánh Linh',
          email: 'customer05@example.com',
          phone: '0912000005',
          subject: 'Mã giảm giá',
          message: 'Mã WELCOME10 áp dụng thế nào?',
          status: 'resolved',
        },
        {
          id: 6,
          name: 'Đỗ Tuấn Kiệt',
          email: 'customer06@example.com',
          phone: '0912000006',
          subject: 'Theo dõi đơn hàng',
          message: 'Đơn hàng của tôi đang ở đâu?',
          status: 'processing',
        },
        {
          id: 7,
          name: 'Bùi Ngọc Mai',
          email: 'customer07@example.com',
          phone: '0912000007',
          subject: 'Góp ý website',
          message: 'Giao diện dễ dùng, nên thêm chat hỗ trợ.',
          status: 'new',
        },
        {
          id: 8,
          name: 'Hoàng Đức Nam',
          email: 'customer08@example.com',
          phone: '0912000008',
          subject: 'Thanh toán lỗi',
          message: 'Tôi thanh toán Paypal bị lỗi.',
          status: 'processing',
        },
        {
          id: 9,
          name: 'Đặng Thảo Nhi',
          email: 'customer09@example.com',
          phone: '0912000009',
          subject: 'Hoàn tiền',
          message: 'Khi nào tôi nhận được hoàn tiền?',
          status: 'resolved',
        },
        {
          id: 10,
          name: 'Cao Minh Quân',
          email: 'customer10@example.com',
          phone: '0912000010',
          subject: 'Báo lỗi',
          message: 'Trang sản phẩm tải hơi chậm.',
          status: 'new',
        },
      ],
    );

    await this.insertRows(
      queryRunner,
      'banners',
      [
        'id',
        'title',
        'image_url',
        'link_url',
        'position',
        'sort_order',
        'is_active',
      ],
      [
        {
          id: 1,
          title: 'Sale công nghệ tháng 4',
          image_url: 'banners/sale-april.jpg',
          link_url: '/products',
          position: 'home',
          sort_order: 1,
          is_active: true,
        },
        {
          id: 2,
          title: 'iPhone ưu đãi lớn',
          image_url: 'banners/iphone-sale.jpg',
          link_url: '/products/iphone-15-128gb',
          position: 'home',
          sort_order: 2,
          is_active: true,
        },
        {
          id: 3,
          title: 'Laptop cho sinh viên',
          image_url: 'banners/laptop-student.jpg',
          link_url: '/categories/laptop',
          position: 'home',
          sort_order: 3,
          is_active: true,
        },
        {
          id: 4,
          title: 'Phụ kiện giá tốt',
          image_url: 'banners/accessories.jpg',
          link_url: '/categories/phu-kien',
          position: 'home',
          sort_order: 4,
          is_active: true,
        },
        {
          id: 5,
          title: 'Tai nghe chống ồn',
          image_url: 'banners/headphone.jpg',
          link_url: '/categories/tai-nghe',
          position: 'home',
          sort_order: 5,
          is_active: true,
        },
        {
          id: 6,
          title: 'Flash sale cuối tuần',
          image_url: 'banners/weekend.jpg',
          link_url: '/promotions',
          position: 'sidebar',
          sort_order: 1,
          is_active: true,
        },
        {
          id: 7,
          title: 'Miễn phí vận chuyển',
          image_url: 'banners/freeship.jpg',
          link_url: '/cart',
          position: 'sidebar',
          sort_order: 2,
          is_active: true,
        },
        {
          id: 8,
          title: 'Gaming gear',
          image_url: 'banners/gaming.jpg',
          link_url: '/categories/ban-phim',
          position: 'home',
          sort_order: 6,
          is_active: true,
        },
        {
          id: 9,
          title: 'Camera an ninh',
          image_url: 'banners/camera.jpg',
          link_url: '/categories/camera-an-ninh',
          position: 'home',
          sort_order: 7,
          is_active: false,
        },
        {
          id: 10,
          title: 'Banner thử nghiệm',
          image_url: 'banners/test.jpg',
          link_url: null,
          position: 'footer',
          sort_order: 1,
          is_active: false,
        },
      ],
    );

    await this.insertRows(
      queryRunner,
      'settings',
      ['id', 'setting_key', 'setting_value', 'value_type', 'description'],
      [
        {
          id: 1,
          setting_key: 'site_name',
          setting_value: 'Ecommerce Basic Plus',
          value_type: 'string',
          description: 'Tên website',
        },
        {
          id: 2,
          setting_key: 'site_logo',
          setting_value: 'logo.png',
          value_type: 'string',
          description: 'Logo website',
        },
        {
          id: 3,
          setting_key: 'support_email',
          setting_value: 'support@ecommerce.test',
          value_type: 'string',
          description: 'Email hỗ trợ',
        },
        {
          id: 4,
          setting_key: 'support_phone',
          setting_value: '0378519357',
          value_type: 'string',
          description: 'Số điện thoại hỗ trợ',
        },
        {
          id: 5,
          setting_key: 'default_shipping_fee',
          setting_value: '30000',
          value_type: 'number',
          description: 'Phí vận chuyển mặc định',
        },
        {
          id: 6,
          setting_key: 'free_shipping_min_order',
          setting_value: '2000000',
          value_type: 'number',
          description: 'Giá trị đơn tối thiểu để miễn phí vận chuyển',
        },
        {
          id: 7,
          setting_key: 'allow_cod',
          setting_value: 'true',
          value_type: 'boolean',
          description: 'Cho phép thanh toán COD',
        },
        {
          id: 8,
          setting_key: 'allow_online_payment',
          setting_value: 'true',
          value_type: 'boolean',
          description: 'Cho phép thanh toán online',
        },
        {
          id: 9,
          setting_key: 'bank_account_name',
          setting_value: 'NGUYEN TRI DUNG',
          value_type: 'string',
          description: 'Tên tài khoản ngân hàng',
        },
        {
          id: 10,
          setting_key: 'bank_account_number',
          setting_value: '0123456789',
          value_type: 'string',
          description: 'Số tài khoản ngân hàng',
        },
        {
          id: 11,
          setting_key: 'bank_name',
          setting_value: 'VCB',
          value_type: 'string',
          description: 'Tên ngân hàng',
        },
        {
          id: 12,
          setting_key: 'facebook_url',
          setting_value: 'https://facebook.com/ecommerce-basic-plus',
          value_type: 'string',
          description: 'Facebook fanpage',
        },
        {
          id: 13,
          setting_key: 'maintenance_mode',
          setting_value: 'false',
          value_type: 'boolean',
          description: 'Chế độ bảo trì',
        },
        {
          id: 14,
          setting_key: 'seo_keywords',
          setting_value: 'ecommerce, nestjs, mysql, typeorm',
          value_type: 'string',
          description: 'Từ khóa SEO',
        },
        {
          id: 15,
          setting_key: 'homepage_sections',
          setting_value:
            '{"featured":true,"newProducts":true,"bestSellers":true}',
          value_type: 'json',
          description: 'Cấu hình khối trang chủ',
        },
      ],
    );

    await this.insertRows(
      queryRunner,
      'inventory_logs',
      [
        'id',
        'product_id',
        'user_id',
        'type',
        'quantity',
        'quantity_before',
        'quantity_after',
        'note',
      ],
      [
        {
          id: 1,
          product_id: 1,
          user_id: 3,
          type: 'import',
          quantity: 50,
          quantity_before: 0,
          quantity_after: 50,
          note: 'Nhập kho ban đầu',
        },
        {
          id: 2,
          product_id: 1,
          user_id: 3,
          type: 'order',
          quantity: -1,
          quantity_before: 46,
          quantity_after: 45,
          note: 'Trừ kho đơn ORD-202604-0001',
        },
        {
          id: 3,
          product_id: 2,
          user_id: 3,
          type: 'import',
          quantity: 40,
          quantity_before: 0,
          quantity_after: 40,
          note: 'Nhập kho ban đầu',
        },
        {
          id: 4,
          product_id: 2,
          user_id: 3,
          type: 'order',
          quantity: -1,
          quantity_before: 39,
          quantity_after: 38,
          note: 'Trừ kho đơn ORD-202604-0002',
        },
        {
          id: 5,
          product_id: 3,
          user_id: 4,
          type: 'import',
          quantity: 25,
          quantity_before: 0,
          quantity_after: 25,
          note: 'Nhập kho ban đầu',
        },
        {
          id: 6,
          product_id: 3,
          user_id: 4,
          type: 'order',
          quantity: -1,
          quantity_before: 25,
          quantity_after: 24,
          note: 'Trừ kho đơn ORD-202604-0015',
        },
        {
          id: 7,
          product_id: 4,
          user_id: 4,
          type: 'import',
          quantity: 22,
          quantity_before: 0,
          quantity_after: 22,
          note: 'Nhập kho ban đầu',
        },
        {
          id: 8,
          product_id: 4,
          user_id: 4,
          type: 'order',
          quantity: -1,
          quantity_before: 21,
          quantity_after: 20,
          note: 'Trừ kho đơn ORD-202604-0003',
        },
        {
          id: 9,
          product_id: 9,
          user_id: 3,
          type: 'import',
          quantity: 65,
          quantity_before: 0,
          quantity_after: 65,
          note: 'Nhập kho phụ kiện',
        },
        {
          id: 10,
          product_id: 9,
          user_id: 3,
          type: 'order',
          quantity: -1,
          quantity_before: 61,
          quantity_after: 60,
          note: 'Trừ kho đơn ORD-202604-0016',
        },
        {
          id: 11,
          product_id: 13,
          user_id: 4,
          type: 'import',
          quantity: 100,
          quantity_before: 0,
          quantity_after: 100,
          note: 'Nhập kho sạc nhanh',
        },
        {
          id: 12,
          product_id: 13,
          user_id: 4,
          type: 'order',
          quantity: -2,
          quantity_before: 92,
          quantity_after: 90,
          note: 'Trừ kho đơn ORD-202604-0004',
        },
        {
          id: 13,
          product_id: 14,
          user_id: 3,
          type: 'import',
          quantity: 18,
          quantity_before: 0,
          quantity_after: 18,
          note: 'Nhập kho màn hình',
        },
        {
          id: 14,
          product_id: 14,
          user_id: 3,
          type: 'order',
          quantity: -1,
          quantity_before: 16,
          quantity_after: 15,
          note: 'Trừ kho đơn ORD-202604-0014',
        },
        {
          id: 15,
          product_id: 19,
          user_id: 4,
          type: 'adjust',
          quantity: -5,
          quantity_before: 5,
          quantity_after: 0,
          note: 'Điều chỉnh tồn kho hết hàng',
        },
        {
          id: 16,
          product_id: 20,
          user_id: 4,
          type: 'adjust',
          quantity: -2,
          quantity_before: 2,
          quantity_after: 0,
          note: 'Tạm ngừng bán sản phẩm',
        },
        {
          id: 17,
          product_id: 10,
          user_id: 3,
          type: 'return',
          quantity: 1,
          quantity_before: 24,
          quantity_after: 25,
          note: 'Nhập lại hàng hoàn trả',
        },
        {
          id: 18,
          product_id: 16,
          user_id: 3,
          type: 'order',
          quantity: -1,
          quantity_before: 41,
          quantity_after: 40,
          note: 'Trừ kho đơn ORD-202604-0018',
        },
        {
          id: 19,
          product_id: 17,
          user_id: 4,
          type: 'order',
          quantity: -1,
          quantity_before: 32,
          quantity_after: 31,
          note: 'Trừ kho đơn ORD-202604-0020',
        },
        {
          id: 20,
          product_id: 18,
          user_id: 4,
          type: 'order',
          quantity: -1,
          quantity_before: 29,
          quantity_after: 28,
          note: 'Trừ kho đơn ORD-202604-0008',
        },
      ],
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('SET FOREIGN_KEY_CHECKS = 0');

    const tables = [
      'inventory_logs',
      'settings',
      'banners',
      'contacts',
      'notifications',
      'reviews',
      'payments',
      'order_items',
      'orders',
      'coupons',
      'cart_items',
      'carts',
      'addresses',
      'product_images',
      'products',
      'categories',
      'refresh_tokens',
      'users',
      'roles',
    ];

    for (const table of tables) {
      await queryRunner.query(`DELETE FROM \`${table}\``);
      await queryRunner.query(`ALTER TABLE \`${table}\` AUTO_INCREMENT = 1`);
    }

    await queryRunner.query('SET FOREIGN_KEY_CHECKS = 1');
  }
}
